//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalLaboratoryNumber20WebAPI.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodServiceOfUser
    {
        public int BloodId { get; set; }
        public int ServiceCode { get; set; }
        public string Result { get; set; }
        public System.DateTime FinishedDateTime { get; set; }
        public bool IsAccepted { get; set; }
        public int BloodStatusId { get; set; }
        public int AnalyzerId { get; set; }
        public int UserId { get; set; }
    
        public virtual Analyzer Analyzer { get; set; }
        public virtual Blood Blood { get; set; }
        public virtual BloodStatus BloodStatus { get; set; }
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
    }
}
