//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalLaboratoryNumber20WebAPI.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceAddress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InsuranceAddress()
        {
            this.InsuranceCompany = new HashSet<InsuranceCompany>();
        }
    
        public int InsuranceAddressId { get; set; }
        public string AddressName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceCompany> InsuranceCompany { get; set; }
    }
}
