//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalLaboratoryNumber20WebAPI.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InsuranceCompany()
        {
            this.Patient = new HashSet<Patient>();
        }
    
        public int InsuranceCompanyId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string InsuranceName { get; set; }
        public int AddressId { get; set; }
        public string INN { get; set; }
        public string BIK { get; set; }
        public string PaymentAccount { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual InsuranceAddress InsuranceAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patient> Patient { get; set; }
    }
}
